name: proj_env_2
channels:
  - cvxgrp
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - absl-py=0.5.0
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - astor=0.7.1
  - attrs=18.2.0
  - automat=0.7.0
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2018.10.15
  - certifi=2018.10.15
  - cffi=1.11.5
  - colorama=0.3.9
  - constantly=15.1.0
  - cryptography=2.3.1
  - cryptography-vectors=2.3.1
  - cvxpy=0.4.10
  - cython=0.28.5
  - decorator=4.3.0
  - dill=0.2.8.2
  - ecos=2.0.5
  - entrypoints=0.2.3
  - fastcache=1.0.2
  - gast=0.2.0
  - grpcio=1.12.1
  - h5py=2.8.0
  - hdf5=1.10.2
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icc_rt=2017.0.4
  - icu=58.2
  - idna=2.7
  - incremental=17.5.0
  - intel-openmp=2019.0
  - ipykernel=5.1.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - keras-applications=1.0.6
  - keras-preprocessing=1.0.5
  - libiconv=1.14
  - libpng=1.6.34
  - libprotobuf=3.5.2
  - libsodium=1.0.16
  - libxml2=2.9.5
  - libxslt=1.1.32
  - lxml=4.2.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=2.6.11
  - markupsafe=1.0
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - msys2-conda-epoch=20160418
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.7.0
  - numpy=1.15.2
  - numpy-base=1.15.2
  - openssl=1.0.2p
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.3.1
  - pickleshare=0.7.5
  - pip=18.1
  - prometheus_client=0.4.0
  - prompt_toolkit=1.0.15
  - protobuf=3.5.2
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycparser=2.19
  - pygments=2.2.0
  - pyhamcrest=1.9.0
  - pyopenssl=18.0.0
  - pyqt=5.6.0
  - pyreadline=2.1
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywin32=223
  - pywinpty=0.5.4
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.6.2
  - qtconsole=4.4.3
  - scipy=1.1.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.4.3
  - simplegeneric=0.8.1
  - sip=4.19.8
  - sqlite=3.22.0
  - tensorboard=1.9.0
  - tensorflow=1.9.0
  - tensorflow-base=1.9.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - toolz=0.9.0
  - tornado=5.1.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - vc=14
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - werkzeug=0.14.1
  - wheel=0.32.1
  - widgetsnbextension=3.4.2
  - wincertstore=0.2
  - winpty=0.4.3
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - pip:
    - bleach==3.0.2
    - cvxcanon==0.1.1
    - future==0.16.0
    - keras==2.2.4
    - knnimpute==0.1.0
    - multiprocess==0.70.4
    - np-utils==0.5.5.2
    - osqp==0.4.1
    - scikit-learn==0.20.0
    - scs==1.2.6
    - six==1.11.0
    - webencodings==0.5.1

